const Datos = [
    {
        Departamento: "Amazonas",
        Provincia: "Chachapoyas",
        Distrito: "Chachapoyas",
        IdUbigeo: "010101",
        precio: 250,
        edad: 24,
        decription: "hola como estas ven conmigo a psarla bien, todos juntos",
        img: "https://www.caracteristicass.de/wp-content/uploads/2022/02/caracteristicas-de-la-cuenca-amazonica.jpg",
        lng: -77.867796,
        lat: -6.217823,
    },
    {
        Departamento: "Arequipa",
        Provincia: "Melgar",
        Distrito: "Yanahuara",
        IdUbigeo: "010102",
        precio: 250,
        edad: 24,
        decription: "hola como estas ven conmigo a psarla bien, todos juntos",
        img: "https://media.gettyimages.com/photos/high-angle-view-of-cityscape-against-sky-picture-id1238003405?s=612x612",
        lng: -71.535064,
        lat: -16.404379,
    },
    {
        Departamento: "Piura",
        Provincia: "Catacaos",
        Distrito: "Grau",
        IdUbigeo: "010103",
        precio: 250,
        edad: 24,
        decription: "hola como estas ven conmigo a psarla bien, todos juntos",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRq8dIw-TsZQXwaCOUaWrnQfIqgiRlhmkM35wRyhNo9H3DJS4MkzM2PKCuwkCKgMO1B4YQ&usqp=CAU",
        lng: -80.68363,
        lat: -5.193256,
    },

    {
        Departamento: "Loreto",
        Provincia: "Esperanza",
        Distrito: "Minarumi",
        IdUbigeo: "010121",
        precio: 250,
        edad: 24,
        decription: "hola como estas ven conmigo a psarla bien, todos juntos",
        img: "https://www.actualidadambiental.pe/wp-content/uploads/2021/07/portada-opcion-1-foto-Kevin-Arce-DanielPinedo-1-700x466.jpg",
        lng: -73.268038,
        lat: -3.752405,
    },
    {
        Departamento: "Lima",
        Provincia: "Lima",
        Distrito: "Comas",
        IdUbigeo: "010200",
        precio: 250,
        edad: 24,
        decription: "hola como estas ven conmigo a psarla bien, todos juntos",
        img: "https://www.rubenyelmundo.com/wp-content/uploads/2021/11/Captura-de-pantalla-2021-11-24-a-las-16.00.52.jpg",
        lng: -77.022161,
        lat: -12.069475,
    },
    {
        Departamento: "Junin",
        Provincia: "Huancayo",
        Distrito: "Shupaca",
        IdUbigeo: "010201",
        precio: 250,
        edad: 24,
        decription: "hola como estas ven conmigo a psarla bien, todos juntos",
        img: "https://comollegara.info/wp-content/uploads/2021/08/Como-llegar-a-Junin-desde-Lima-.jpg",
        lng: -75.992732,
        lat: -11.156381,
    },
    {
        Departamento: "Puno",
        Provincia: "Pukara",
        Distrito: "El condor",
        IdUbigeo: "010202",
        precio: 250,
        edad: 24,
        decription: "hola como estas ven conmigo a psarla bien, todos juntos",
        img: "https://noticias-pe.laiglesiadejesucristo.org/media/960x540/Puno-plaza-de-armas.jpg",
        lng: -70.024801,
        lat: -15.827697,
    },
    {
        Departamento: "Ica",
        Provincia: "Ayabaca",
        Distrito: "Huaca China",
        IdUbigeo: "010203",
        precio: 250,
        edad: 24,
        decription: "hola como estas ven conmigo a psarla bien, todos juntos",
        img: "https://jcmagazine.com/wp-content/uploads/2019/11/ica-peru.jpg",
        lng: -75.745481,
        lat: -14.088913,
    },
    {
        Departamento: "San Martín",
        Provincia: "Chirimoto",
        Distrito: "La Primavera",
        IdUbigeo: "220201",
        precio: 250,
        edad: 24,
        decription: "hola como estas ven conmigo a psarla bien, todos juntos",
        img: "https://cdn.www.gob.pe/uploads/document/file/2152542/standard_San%20Mart%C3%ADn%20%20%281%29.jpeg.jpeg",
        lng: -77.15408,
        lat: -6.815448,
    },
    {
        Departamento: "Tacna",
        Provincia: "Tacna",
        Distrito: "Pocollay",
        IdUbigeo: "230104",
        precio: 250,
        edad: 24,
        decription: "hola como estas ven conmigo a psarla bien, todos juntos",
        img: "https://peru.info/Portals/0/Images/Productos/6/178-imagen-930171942022.jpg",
        lng: -70.244394,
        lat: -18.014114,
    },
    {
        Departamento: "Ucayali",
        Provincia: "Pucallpa",
        Distrito: "Union",
        IdUbigeo: "250400",
        precio: 250,
        edad: 24,
        decription: "hola como estas ven conmigo a psarla bien, todos juntos",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Ucayali_basin.jpg/270px-Ucayali_basin.jpg",
        lng: -75.745481,
        lat: -14.088913,
    },
];
export default Datos;
